---
title: "Publication bias"
date: "Last updated `r format(Sys.time(), '%Y.%m.%d')`"
output: 
  html_document:
    toc: true
    code_folding: hide
    code_download: true
    css: styles.css
fontsize: 11pt
spacing: single
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
#knitr::opts_chunk$set(eval = FALSE)

options(pillar.sigfig = 4) # ensure tibble include 4 digits
options(tibble.width = Inf)
options(dplyr.print_min = 310)
options(scipen = 10)
options(dplyr.summarise.inform = FALSE) # Avoids summarize info from tidyverse

library(DT)
library(kableExtra)

```

```{r, echo=FALSE}

library(tidyverse)
library(robvis)
library(purrr)
library(metafor)
library(patchwork)
library(clubSandwich)
library(wildmeta)
library(gt)

library(puniform)
library(tidyverse) # for tidying
library(janitor)   # for tidying variable names
library(boot)      # for bootstrapping
library(tictoc) 


# Loading in helper function used to calculate effect size and conduct the analysis
source_path <- if (isTRUE(getOption('knitr.in.progress'))) "Helpers.R" else "ES calc/Helpers.R"

source(source_path)
```

```{r}
# Loading data set
reintergation_dat <- 
  if (isTRUE(getOption('knitr.in.progress'))) {
    readRDS("reintergation_dat.rds") 
  } else {
    readRDS("ES calc/reintergation_dat.rds")
  }
```

```{r, warning = FALSE, message = FALSE, echo = FALSE}
reintergation_dat |>  
  select(author_year, N_t, N_c, gt, vgt, Wgt, no_protocol = conventional, Overall_rob = Overall) |> 
  kable(digits=2)  |> 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    font_size = 10
  ) |> 
  scroll_box(width = "100%", height = "300px", fixed_thead = TRUE) 
```

# Funnel plots {.tabset}

## Overall

1

## Alcohol and drug abuse/misuse

2

## Hope, Empowerment & Self-efficacy

3

## Social functioning (degree of impairment)

4

## Wellbeing and quality of life

5

